<a href="https://colab.research.google.com/github/nvaughn/Pytorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__


'2.0.1+cu118'

# The Tensor

A tensor is a mathematical object that generalizes scalars, vectors, and matrices into higher-dimensional spaces. It’s an array of numbers and functions encompassing physical quantities, geometric transformations, and various mathematical entities. In a way, tensors are containers that present data in n-dimensions. They are typically grids of numbers called N-way arrays.

### https://pytorch.org/docs/stable/tensors.html

## The Scalar

A scalar is a single number.  This is known as a zero dimension tensor.

In [2]:
scalar = torch.tensor(42)

scalar

tensor(42)

We can check the dimensions of a tensor with the **ndim** attribute



In [3]:
scalar.ndim

0

To retrieve the value use the **item()** method

In [4]:
scalar.item()

42

# The Vector

A **vector** is a single dimension **tensor** that can have multiple numbers.  

###NOTE: You must group the members of the vector in an array []
###NOTE: You can quickly tell how many demensions a tensor has by counting the opening square brackets

In [5]:
vector = torch.tensor([42, 7])
vector
vector.ndim

1

The **shape** attribute details how the members are arranged in the tensor

In [6]:
vector.shape

torch.Size([2])

# The Matrix

A matrix is two dimensional tensor.  Think scoreboard

### NOTE: Torch requires all tensors to be one argument.  So the two dimensions must be inclosed in a array.

### NOTE: Again count the number of opening (left || right) brackets to get the number of dimensions. Or just check the **ndim** attribute

In [7]:
MATRIX = torch.tensor([[42, 7], [6,1]])
MATRIX
MATRIX.ndim


2

In [8]:
MATRIX.shape


torch.Size([2, 2])

# The Tensor

Although all of these are tensors. We generally refer to zero dimension tensors as scalars, One dimensional tensors as vectors, Two dimensional tensors as matrixs and any higher number of dimensions as tensors

When visualizing a 3 dimensional tensor think Spreadsheet

In [9]:
TENSOR = torch.tensor([[[42,7], [6,1], [48,8]]])
TENSOR
TENSOR.ndim

3

In [10]:
TENSOR.shape

torch.Size([1, 3, 2])

## NOTE: scalars and vectors are normally listed in lowercase and Matrixs and Tensor uppercase

## Creating randomized tensors

(This is normally how things start off when processing data. Then we use functions to adjust the values of the tensors)

In [11]:
RANDOM_MATRIX = torch.rand(3,2)
RANDOM_MATRIX


tensor([[0.4614, 0.6837],
        [0.9892, 0.6110],
        [0.5178, 0.2509]])

In [12]:
RANDOM_TENSOR = torch.rand(3,4)
RANDOM_TENSOR

tensor([[0.8665, 0.6328, 0.6417, 0.8427],
        [0.8683, 0.0077, 0.9816, 0.4947],
        [0.9481, 0.7733, 0.1747, 0.9187]])

## Random Image Example

In [13]:
random_image_tensor = torch.rand(size = (224, 224, 3))
random_image_tensor

tensor([[[0.3687, 0.9506, 0.5882],
         [0.8908, 0.2584, 0.4176],
         [0.3582, 0.7769, 0.9909],
         ...,
         [0.6837, 0.7045, 0.5380],
         [0.6918, 0.5665, 0.8076],
         [0.5572, 0.6219, 0.1744]],

        [[0.8500, 0.2150, 0.2111],
         [0.3563, 0.5003, 0.1792],
         [0.5303, 0.3746, 0.4910],
         ...,
         [0.5753, 0.3327, 0.7855],
         [0.5102, 0.8359, 0.4915],
         [0.5158, 0.2836, 0.0375]],

        [[0.3383, 0.9383, 0.6941],
         [0.7779, 0.9457, 0.3660],
         [0.3624, 0.2970, 0.3620],
         ...,
         [0.8846, 0.6395, 0.7752],
         [0.7989, 0.6739, 0.1884],
         [0.2077, 0.5277, 0.5842]],

        ...,

        [[0.7479, 0.4064, 0.6990],
         [0.1658, 0.8485, 0.9852],
         [0.8512, 0.2181, 0.8598],
         ...,
         [0.6205, 0.2422, 0.1839],
         [0.6571, 0.5917, 0.4174],
         [0.9202, 0.1450, 0.0980]],

        [[0.7450, 0.4990, 0.8427],
         [0.9546, 0.0994, 0.5267],
         [0.

In [14]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [15]:
random_image_tensor.ndim

3

# Zeroing Out Tensors

At times you may need to fill a tensors with zeros when applying a mask.  Use the torch.zeros() function

In [16]:
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor, zeros_tensor.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

## We can do the same with ones using torch.ones()

In [17]:
ones_tensor = torch.ones(size=(3,4))
ones_tensor, ones_tensor.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Or create a range with torch.range()

In [18]:
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
zero_to_ten_with_step = torch.arange(start=0, end=10, step=1)
zero_to_ten_with_step

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
zero_to_ten_with_step2 = torch.arange(start=0, end=10, step=2)
zero_to_ten_with_step2

tensor([0, 2, 4, 6, 8])

## Creating duplicate existing tensor shape with 1's or 0's

In [21]:
duplicate_w_zeros = torch.zeros_like(input=zero_to_ten)
duplicate_w_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Pytorch Tensors can have a number of different datatypes. You can specify the datatype with the dtype argument at tensor creation. Some are good for CPU some are good for GPU.  If you see something that states CUDA.. This is GPU.

For a list of all supported tensor dtypes review: https://pytorch.org/docs/stable/tensors.html#data-types

In [22]:
float_32_tensor = torch.tensor([[[42,7], [6,1], [48,8]]], dtype=torch.float32, device=None, requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.shape

(tensor([[[42.,  7.],
          [ 6.,  1.],
          [48.,  8.]]]),
 torch.float32,
 device(type='cpu'),
 torch.Size([1, 3, 2]))

## Note the defaults with (None)

In [23]:
default_dtype_tensor = torch.tensor([[[42,7], [6,1], [48,8]]], dtype=None, device=None, requires_grad=False)
default_dtype_tensor, default_dtype_tensor.dtype, default_dtype_tensor.device, default_dtype_tensor.shape

(tensor([[[42,  7],
          [ 6,  1],
          [48,  8]]]),
 torch.int64,
 device(type='cpu'),
 torch.Size([1, 3, 2]))

In [24]:
print(default_dtype_tensor)
print(f"Shape of tensor: {default_dtype_tensor.shape}")
print(f"Datatype of tensor: {default_dtype_tensor.dtype}")
print(f"Device tensor is stored on: {default_dtype_tensor.device}")

tensor([[[42,  7],
         [ 6,  1],
         [48,  8]]])
Shape of tensor: torch.Size([1, 3, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


## Tensor operations for manipulating Tensors
+ addition
- subtraction
* element wise multiplication
/ division
@ Matrix Multiplication

## NOTE: Most operations will not modify the existing tensor instead it will create a new one.  However, functions that end with a _  (add_) will run inplace and modify the existing tensor


The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

Operation	Calculation	Code
Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)




 | opperand  | Meaning    | Torch Function|
 |-------------|-------------|-------------|
 | +           | addition         | NONE   |
 | -           | subtraction      | NONE   |
 | *           | multiplication   | torch.mul()   |
 | /           | division         | NONE     |
 | @           | matrix multiplication| torch.matmul()   |

 ## Matrix Multiplication Rules

### The inner dimensions must match.
### The resulting matrix has the shape of the outer dimensions.

See Pytorch Docs for all Matrix Multiplication rules: https://pytorch.org/docs/stable/generated/torch.matmul.html



In [25]:
# EXAMPLE - Element Wise Multiplication

mul_tensor = torch.tensor([1,2,3])
mul_tensor * mul_tensor


tensor([1, 4, 9])

In [26]:
# Example - Matrix Multiplication
mul_tensor @ mul_tensor

tensor(14)

In [27]:
torch.matmul(mul_tensor, mul_tensor)

tensor(14)

## Matrix multiplication is the lync pin in M/L and Neural Networks.  If your matrix's are compatable (see rule 1), things will not work.  You can use use the transpose function to flip a offending matrix so matrix multiplication works

In [28]:
## Example transpose

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [30]:
tensor_A @ tensor_B

RuntimeError: ignored

## Fix the above error by one of the matrixs

In [31]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [32]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Aggregation OR Finding the min, max, mean, sum

.min  .max .mean .sum

In [33]:
x = torch.arange(0, 100, 10)

In [34]:
x.min()

tensor(0)

In [35]:
x.max()

tensor(90)

In [36]:
x.type(torch.float32).mean()

tensor(45.)

In [37]:
x.sum()

tensor(450)

### Find the min/max index

In [38]:
x.argmax()


tensor(9)

In [39]:
x.argmin()

tensor(0)

# tensors & NumPy

Pytorch tensors and NumPy arrays can be easily converted to each other

In [40]:
import numpy as np
array = np.arange(7.0, 42.0)
tensor = torch.from_numpy(array)
array, tensor

(array([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.,
        20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39., 40., 41.]),
 tensor([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.,
         21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34.,
         35., 36., 37., 38., 39., 40., 41.], dtype=torch.float64))

## Note the datatype is float64 by default.  Many M/L task require float32. We can convert the tensor to float32

In [41]:
tensor = torch.from_numpy(array).type(torch.float32)

In [42]:
tensor

tensor([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.,
        21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34.,
        35., 36., 37., 38., 39., 40., 41.])

In [43]:
tensor.dtype

torch.float32

We can convert from a Pytorch tensor to numPy array by running .numpy() on the array

In [44]:
tensor.numpy()

array([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.,
       20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 34., 35., 36., 37., 38., 39., 40., 41.], dtype=float32)

Randomness is great.  But in order to perform repeatable experiments we need to set a seed which will make the random output the same each time executed.

We need to use the manual_seed() function with the rand() function.

Review the Pytorch docs on reproducibility: https://pytorch.org/docs/stable/notes/randomness.html

In [45]:
SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"verify both tensors are exactly the same\n")
random_tensor_C == random_tensor_D

verify both tensors are exactly the same



tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Deep Learning is very compute intensive.  If you have access to a GPU it can do the calculations such as Matrix Multiplication 1000 times faster than a cpu. To check if you local machine has a GPU from a Jupyter notebook execute '!nvidia-smi' from colab or Kaggle type notebooks check with torch.cuda.is_available() function

In [46]:
torch.cuda.is_available()


True

While a GPU is nice it may not be available in your environment.  You can create device agnostic code that will run on either CPU or GPU.

In [47]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

If you have multiple GPU's you can actually spread your workload across them all or run certain calculations on certain GPU's.  To check how man GPU's you have access to run torch.cuda.device_count()



In [48]:
torch.cuda.device_count()


1

### If needed you can move a tensor from a CPU to a GPU (SPEED)


In [52]:

# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

NOTE: Numpy is doesn't support GPU's.  So to move something from a GPU to a CPU we run the .cpu() function

In [54]:
tensor_on_gpu.numpy()


TypeError: ignored

In [55]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### NOTE: The original tensor stays on the GPU.  It just made a copy on the CPU

In [57]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')